<h1>Cadastro de Produtos</h1>

<?php echo $this->form()->openTag($form); ?>
	<div class="form-group">
		<label for="">Nome</label>
		<?php 
			echo $this->formInput($form->get('nome'));
			echo $this->formElementErrors()->render($form->get('nome'));
		?>
	</div>

	<div class="form-group">
		<label for="">Preço</label>
		<?php echo $this->formInput($form->get('preco')) ?>
	</div>

	<div class="form-group">
		<label for="">Descrição</label>
		<?php echo $this->formTextarea($form->get('descricao')) ?>
	</div>

	<div class="form-group">
		<input type="submit" value="salvar" class="btn btn-primary">
	</div>
<?php echo $this->form()->closeTag($form) ?>