<h1>Cadastro de Produtos</h1>

<form method="post" action ="\Index\create">
	<div class="form-group">
		<label for="">Nome</label>
		<input type="text" name="nome" class="form-control">
	</div>

	<div class="form-group">
		<label for="">Preço</label>
		<input type="number" name="preco" class="form-control">
	</div>

	<div class="form-group">
		<label for="">Descrição</label>
		<textarea class="form-control" name="descricao"></textarea>
	</div>

	<div class="form-group">
		<input type="submit" value="salvar" class="btn btn-primary">
	</div>
</form>