<h1>Listagem de Produtos</h1>

<table class="table">
	<thead>
		<tr>
			<th>Nome</th>			
			<th>Preço</th>
			<th>Categoria</th>
			<th>Descrição</th>
			<th>Ações</th>
		</tr>
	</thead>

	<tbody>
		<?php foreach($produtos as $produto):  ?>
			<tr>
				<td><?= $produto->getNome() ?></td>
				<td><?= $produto->getPreco() ?></td>
				<td><?= $produto->getCategoria()->getNome() ?></td>
				<td><?= $produto->getDescricao() ?></td>				
				<td>
					<a href="<?= $this->url('application', ['action' => 'delete', 'id' => $produto->getId()]); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span></a>
					<a href="<?= $this->url('application', ['action' => 'update', 'id' => $produto->getId()]); ?>" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>					
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>	
</table>

<?php echo $this->paginationHelper($produtos, $qtdPorPagina, '/Produtos') ?>