<h1>Editar Produto</h1>

<form method="post" action="<?= $this->url('application', ['action' => 'update'])?>">
	<div class="form-group">
		<label for="">Nome</label>
		<input type="text" name="nome" class="form-control" value="<?=$produto->getNome()?>">
	</div>

	<div class="form-group">
		<label for="">Preço</label>
		<input type="number" name="preco" class="form-control" value="<?=$produto->getPreco()?>">
	</div>

	<div class="form-group">
		<label for="">Descrição</label>
		<textarea class="form-control" name="descricao"><?=$produto->getDescricao()?></textarea>
	</div>

	<div class="form-group">
		<input type="hidden" value="<?=$produto->getId()?>" name="id">
		<input type="submit" value="salvar" class="btn btn-primary">
	</div>
</form>